grpc:
  server:
    port: 9000

spring:
  application:
    name: NETFLIX
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/graphql?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Root@9641}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true